version: '3.8'

services:
  comicon:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
    depends_on:
      mysql-comicon:
         condition: service_healthy
    networks:
      - comicon-network


  mysql-comicon:
    image: mysql:latest
    container_name: mysql-comicon
    hostname: mysql-comicon
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: comicon
    ports:
      - "3307:3306"
    networks:
      - comicon-network

networks:
  comicon-network:
    driver: bridge